language: php
php:
  - 5.4
  - 5.6
  - nightly
  
before_script: composer install
after_script: vendor/bin/test-reporter

before_install:
  - travis_retry composer self-update
  - travis_retry composer install --dev --no-interaction --prefer-source

script:
  - ./vendor/bin/phpunit

after_script:
  - ./vendor/bin/test-reporter --stdout > codeclimate.json
  - "curl -X POST -d @codeclimate.json -H 'Content-Type: application/json' -H 'User-Agent: Code Climate (PHP Test Reporter v0.1.1)' https://codeclimate.com/test_reports"

addons:
  code_climate:
    repo_token: $CODECLIMATE_REPO_TOKEN

cache:
  directories:
    - vendor