database:
    driver: mysql
    host: 127.0.0.1
    dbname: expressly
    user: root
    password: ''

table:
    merchant: expressly_preferences

provider:
    merchant: Expressly\Provider\MerchantProvider

servlet:
    url: https://buyexpressly.com/expresslymod
    popup: http://buyexpressly.com/website/popup_demo_a_blue/index.php
    popup_mobile: http://buyexpressly.com/website/popup_demo_a_blue/index.php

external:
    hosts:
        default: https://expresslyapp.com/api/v1
        admin: https://expresslyapp.com/api/admin
    routes:
        customer_migrate_start:
            host: default
            method: GET
            uri: /migration/<uuid>
        customer_migrate_cart:
            host: default
            method: GET
            uri: /migration/<uuid>/user
        customer_update:
            host: default
            method: GET
            uri: /
        customer_reset:
            host: default
            method: GET
            uri: /
        customer_order:
            host: default
            method: GET
            uri: /
        merchant_password_create:
            host: admin
            method: POST
            uri: /merchant/password/create
        merchant_password_update:
            host: admin
            method: POST
            uri: /merchant/password/update