validators:
    - { class: Expressly\Validator\UuidValidator, message: Plugin not registered; please register first. }
    - { class: Expressly\Validator\EmailValidator, message: Invalid email address provided. }

routes:
    - Expressly\Route\Ping
    - Expressly\Route\Registered
    - Expressly\Route\UserData
    - Expressly\Route\BatchCustomer
    - Expressly\Route\BatchInvoice
    - Expressly\Route\CampaignMigration
    - Expressly\Route\CampaignPopup

external:
    hosts:
        default: http://prod.expresslyapp.com/api/v2
        admin: http://prod.expresslyapp.com/api/admin
    routes:
        ping:
            host: admin
            method: GET
            uri: /ping
        customer_migrate_popup:
            host: default
            method: GET
            uri: /migration/<uuid>
            validation:
                uuid: uuid_string
        customer_migrate_data:
            host: default
            method: GET
            uri: /migration/<uuid>/user
            validation:
                uuid: uuid_string
        customer_migrate_success:
            host: default
            method: POST
            uri: /migration/<uuid>/success
            validation:
                uuid: uuid_string
        merchant_register:
            host: default
            method: POST
            uri: /plugin/merchant
        merchant_delete:
            host: default
            method: DELETE
            uri: /plugin/merchant/<uuid>
            validation:
                uuid: uuid_string
        banner_request:
            host: default
            method: GET
            uri: /banner/<uuid>?email=<email>
            validation:
                uuid: uuid_string
                email: email

country_code:
    - { iso2: 'AF', iso3: 'AFG', m49: '004' }
    - { iso2: 'AX', iso3: 'ALA', m49: '248' }
    - { iso2: 'AL', iso3: 'ALB', m49: '008' }
    - { iso2: 'DZ', iso3: 'DZA', m49: '012' }
    - { iso2: 'AS', iso3: 'ASM', m49: '016' }
    - { iso2: 'AD', iso3: 'AND', m49: '020' }
    - { iso2: 'AO', iso3: 'AGO', m49: '024' }
    - { iso2: 'AI', iso3: 'AIA', m49: '660' }
    - { iso2: 'AQ', iso3: 'ATA', m49: '010' }
    - { iso2: 'AG', iso3: 'ATG', m49: '028' }
    - { iso2: 'AR', iso3: 'ARG', m49: '032' }
    - { iso2: 'AM', iso3: 'ARM', m49: '051' }
    - { iso2: 'AW', iso3: 'ABW', m49: '533' }
    - { iso2: 'AU', iso3: 'AUS', m49: '036' }
    - { iso2: 'AT', iso3: 'AUT', m49: '040' }
    - { iso2: 'AZ', iso3: 'AZE', m49: '031' }
    - { iso2: 'BS', iso3: 'BHS', m49: '044' }
    - { iso2: 'BH', iso3: 'BHR', m49: '048' }
    - { iso2: 'BD', iso3: 'BGD', m49: '050' }
    - { iso2: 'BB', iso3: 'BRB', m49: '052' }
    - { iso2: 'BY', iso3: 'BLR', m49: '112' }
    - { iso2: 'BE', iso3: 'BEL', m49: '056' }
    - { iso2: 'BZ', iso3: 'BLZ', m49: '084' }
    - { iso2: 'BJ', iso3: 'BEN', m49: '204' }
    - { iso2: 'BM', iso3: 'BMU', m49: '060' }
    - { iso2: 'BT', iso3: 'BTN', m49: '064' }
    - { iso2: 'BO', iso3: 'BOL', m49: '068' }
    - { iso2: 'BA', iso3: 'BIH', m49: '070' }
    - { iso2: 'BW', iso3: 'BWA', m49: '072' }
    - { iso2: 'BV', iso3: 'BVT', m49: '074' }
    - { iso2: 'BR', iso3: 'BRA', m49: '076' }
    - { iso2: 'VG', iso3: 'VGB', m49: '092' }
    - { iso2: 'IO', iso3: 'IOT', m49: '086' }
    - { iso2: 'BN', iso3: 'BRN', m49: '096' }
    - { iso2: 'BG', iso3: 'BGR', m49: '100' }
    - { iso2: 'BF', iso3: 'BFA', m49: '854' }
    - { iso2: 'BI', iso3: 'BDI', m49: '108' }
    - { iso2: 'KH', iso3: 'KHM', m49: '116' }
    - { iso2: 'CM', iso3: 'CMR', m49: '120' }
    - { iso2: 'CA', iso3: 'CAN', m49: '124' }
    - { iso2: 'CV', iso3: 'CPV', m49: '132' }
    - { iso2: 'KY', iso3: 'CYM', m49: '136' }
    - { iso2: 'CF', iso3: 'CAF', m49: '140' }
    - { iso2: 'TD', iso3: 'TCD', m49: '148' }
    - { iso2: 'CL', iso3: 'CHL', m49: '152' }
    - { iso2: 'CN', iso3: 'CHN', m49: '156' }
    - { iso2: 'HK', iso3: 'HKG', m49: '344' }
    - { iso2: 'MO', iso3: 'MAC', m49: '446' }
    - { iso2: 'CX', iso3: 'CXR', m49: '162' }
    - { iso2: 'CC', iso3: 'CCK', m49: '166' }
    - { iso2: 'CO', iso3: 'COL', m49: '170' }
    - { iso2: 'KM', iso3: 'COM', m49: '174' }
    - { iso2: 'CG', iso3: 'COG', m49: '178' }
    - { iso2: 'CD', iso3: 'COD', m49: '180' }
    - { iso2: 'CK', iso3: 'COK', m49: '184' }
    - { iso2: 'CR', iso3: 'CRI', m49: '188' }
    - { iso2: 'CI', iso3: 'CIV', m49: '384' }
    - { iso2: 'HR', iso3: 'HRV', m49: '191' }
    - { iso2: 'CU', iso3: 'CUB', m49: '192' }
    - { iso2: 'CY', iso3: 'CYP', m49: '196' }
    - { iso2: 'CZ', iso3: 'CZE', m49: '203' }
    - { iso2: 'DK', iso3: 'DNK', m49: '208' }
    - { iso2: 'DJ', iso3: 'DJI', m49: '262' }
    - { iso2: 'DM', iso3: 'DMA', m49: '212' }
    - { iso2: 'DO', iso3: 'DOM', m49: '214' }
    - { iso2: 'EC', iso3: 'ECU', m49: '218' }
    - { iso2: 'EG', iso3: 'EGY', m49: '818' }
    - { iso2: 'SV', iso3: 'SLV', m49: '222' }
    - { iso2: 'GQ', iso3: 'GNQ', m49: '226' }
    - { iso2: 'ER', iso3: 'ERI', m49: '232' }
    - { iso2: 'EE', iso3: 'EST', m49: '233' }
    - { iso2: 'ET', iso3: 'ETH', m49: '231' }
    - { iso2: 'FK', iso3: 'FLK', m49: '238' }
    - { iso2: 'FO', iso3: 'FRO', m49: '234' }
    - { iso2: 'FJ', iso3: 'FJI', m49: '242' }
    - { iso2: 'FI', iso3: 'FIN', m49: '246' }
    - { iso2: 'FR', iso3: 'FRA', m49: '250' }
    - { iso2: 'GF', iso3: 'GUF', m49: '254' }
    - { iso2: 'PF', iso3: 'PYF', m49: '258' }
    - { iso2: 'TF', iso3: 'ATF', m49: '260' }
    - { iso2: 'GA', iso3: 'GAB', m49: '266' }
    - { iso2: 'GM', iso3: 'GMB', m49: '270' }
    - { iso2: 'GE', iso3: 'GEO', m49: '268' }
    - { iso2: 'DE', iso3: 'DEU', m49: '276' }
    - { iso2: 'GH', iso3: 'GHA', m49: '288' }
    - { iso2: 'GI', iso3: 'GIB', m49: '292' }
    - { iso2: 'GR', iso3: 'GRC', m49: '300' }
    - { iso2: 'GL', iso3: 'GRL', m49: '304' }
    - { iso2: 'GD', iso3: 'GRD', m49: '308' }
    - { iso2: 'GP', iso3: 'GLP', m49: '312' }
    - { iso2: 'GU', iso3: 'GUM', m49: '316' }
    - { iso2: 'GT', iso3: 'GTM', m49: '320' }
    - { iso2: 'GG', iso3: 'GGY', m49: '831' }
    - { iso2: 'GN', iso3: 'GIN', m49: '324' }
    - { iso2: 'GW', iso3: 'GNB', m49: '624' }
    - { iso2: 'GY', iso3: 'GUY', m49: '328' }
    - { iso2: 'HT', iso3: 'HTI', m49: '332' }
    - { iso2: 'HM', iso3: 'HMD', m49: '334' }
    - { iso2: 'VA', iso3: 'VAT', m49: '336' }
    - { iso2: 'HN', iso3: 'HND', m49: '340' }
    - { iso2: 'HU', iso3: 'HUN', m49: '348' }
    - { iso2: 'IS', iso3: 'ISL', m49: '352' }
    - { iso2: 'IN', iso3: 'IND', m49: '356' }
    - { iso2: 'ID', iso3: 'IDN', m49: '360' }
    - { iso2: 'IR', iso3: 'IRN', m49: '364' }
    - { iso2: 'IQ', iso3: 'IRQ', m49: '368' }
    - { iso2: 'IE', iso3: 'IRL', m49: '372' }
    - { iso2: 'IM', iso3: 'IMN', m49: '833' }
    - { iso2: 'IL', iso3: 'ISR', m49: '376' }
    - { iso2: 'IT', iso3: 'ITA', m49: '380' }
    - { iso2: 'JM', iso3: 'JAM', m49: '388' }
    - { iso2: 'JP', iso3: 'JPN', m49: '392' }
    - { iso2: 'JE', iso3: 'JEY', m49: '832' }
    - { iso2: 'JO', iso3: 'JOR', m49: '400' }
    - { iso2: 'KZ', iso3: 'KAZ', m49: '398' }
    - { iso2: 'KE', iso3: 'KEN', m49: '404' }
    - { iso2: 'KI', iso3: 'KIR', m49: '296' }
    - { iso2: 'KP', iso3: 'PRK', m49: '408' }
    - { iso2: 'KR', iso3: 'KOR', m49: '410' }
    - { iso2: 'KW', iso3: 'KWT', m49: '414' }
    - { iso2: 'KG', iso3: 'KGZ', m49: '417' }
    - { iso2: 'LA', iso3: 'LAO', m49: '418' }
    - { iso2: 'LV', iso3: 'LVA', m49: '428' }
    - { iso2: 'LB', iso3: 'LBN', m49: '422' }
    - { iso2: 'LS', iso3: 'LSO', m49: '426' }
    - { iso2: 'LR', iso3: 'LBR', m49: '430' }
    - { iso2: 'LY', iso3: 'LBY', m49: '434' }
    - { iso2: 'LI', iso3: 'LIE', m49: '438' }
    - { iso2: 'LT', iso3: 'LTU', m49: '440' }
    - { iso2: 'LU', iso3: 'LUX', m49: '442' }
    - { iso2: 'MK', iso3: 'MKD', m49: '807' }
    - { iso2: 'MG', iso3: 'MDG', m49: '450' }
    - { iso2: 'MW', iso3: 'MWI', m49: '454' }
    - { iso2: 'MY', iso3: 'MYS', m49: '458' }
    - { iso2: 'MV', iso3: 'MDV', m49: '462' }
    - { iso2: 'ML', iso3: 'MLI', m49: '466' }
    - { iso2: 'MT', iso3: 'MLT', m49: '470' }
    - { iso2: 'MH', iso3: 'MHL', m49: '584' }
    - { iso2: 'MQ', iso3: 'MTQ', m49: '474' }
    - { iso2: 'MR', iso3: 'MRT', m49: '478' }
    - { iso2: 'MU', iso3: 'MUS', m49: '480' }
    - { iso2: 'YT', iso3: 'MYT', m49: '175' }
    - { iso2: 'MX', iso3: 'MEX', m49: '484' }
    - { iso2: 'FM', iso3: 'FSM', m49: '583' }
    - { iso2: 'MD', iso3: 'MDA', m49: '498' }
    - { iso2: 'MC', iso3: 'MCO', m49: '492' }
    - { iso2: 'MN', iso3: 'MNG', m49: '496' }
    - { iso2: 'ME', iso3: 'MNE', m49: '499' }
    - { iso2: 'MS', iso3: 'MSR', m49: '500' }
    - { iso2: 'MA', iso3: 'MAR', m49: '504' }
    - { iso2: 'MZ', iso3: 'MOZ', m49: '508' }
    - { iso2: 'MM', iso3: 'MMR', m49: '104' }
    - { iso2: 'NA', iso3: 'NAM', m49: '516' }
    - { iso2: 'NR', iso3: 'NRU', m49: '520' }
    - { iso2: 'NP', iso3: 'NPL', m49: '524' }
    - { iso2: 'NL', iso3: 'NLD', m49: '528' }
    - { iso2: 'AN', iso3: 'ANT', m49: '530' }
    - { iso2: 'NC', iso3: 'NCL', m49: '540' }
    - { iso2: 'NZ', iso3: 'NZL', m49: '554' }
    - { iso2: 'NI', iso3: 'NIC', m49: '558' }
    - { iso2: 'NE', iso3: 'NER', m49: '562' }
    - { iso2: 'NG', iso3: 'NGA', m49: '566' }
    - { iso2: 'NU', iso3: 'NIU', m49: '570' }
    - { iso2: 'NF', iso3: 'NFK', m49: '574' }
    - { iso2: 'MP', iso3: 'MNP', m49: '580' }
    - { iso2: 'NO', iso3: 'NOR', m49: '578' }
    - { iso2: 'OM', iso3: 'OMN', m49: '512' }
    - { iso2: 'PK', iso3: 'PAK', m49: '586' }
    - { iso2: 'PW', iso3: 'PLW', m49: '585' }
    - { iso2: 'PS', iso3: 'PSE', m49: '275' }
    - { iso2: 'PA', iso3: 'PAN', m49: '591' }
    - { iso2: 'PG', iso3: 'PNG', m49: '598' }
    - { iso2: 'PY', iso3: 'PRY', m49: '600' }
    - { iso2: 'PE', iso3: 'PER', m49: '604' }
    - { iso2: 'PH', iso3: 'PHL', m49: '608' }
    - { iso2: 'PN', iso3: 'PCN', m49: '612' }
    - { iso2: 'PL', iso3: 'POL', m49: '616' }
    - { iso2: 'PT', iso3: 'PRT', m49: '620' }
    - { iso2: 'PR', iso3: 'PRI', m49: '630' }
    - { iso2: 'QA', iso3: 'QAT', m49: '634' }
    - { iso2: 'RE', iso3: 'REU', m49: '638' }
    - { iso2: 'RO', iso3: 'ROU', m49: '642' }
    - { iso2: 'RU', iso3: 'RUS', m49: '643' }
    - { iso2: 'RW', iso3: 'RWA', m49: '646' }
    - { iso2: 'BL', iso3: 'BLM', m49: '652' }
    - { iso2: 'SH', iso3: 'SHN', m49: '654' }
    - { iso2: 'KN', iso3: 'KNA', m49: '659' }
    - { iso2: 'LC', iso3: 'LCA', m49: '662' }
    - { iso2: 'MF', iso3: 'MAF', m49: '663' }
    - { iso2: 'PM', iso3: 'SPM', m49: '666' }
    - { iso2: 'VC', iso3: 'VCT', m49: '670' }
    - { iso2: 'WS', iso3: 'WSM', m49: '882' }
    - { iso2: 'SM', iso3: 'SMR', m49: '674' }
    - { iso2: 'ST', iso3: 'STP', m49: '678' }
    - { iso2: 'SA', iso3: 'SAU', m49: '682' }
    - { iso2: 'SN', iso3: 'SEN', m49: '686' }
    - { iso2: 'RS', iso3: 'SRB', m49: '688' }
    - { iso2: 'SC', iso3: 'SYC', m49: '690' }
    - { iso2: 'SL', iso3: 'SLE', m49: '694' }
    - { iso2: 'SG', iso3: 'SGP', m49: '702' }
    - { iso2: 'SK', iso3: 'SVK', m49: '703' }
    - { iso2: 'SI', iso3: 'SVN', m49: '705' }
    - { iso2: 'SB', iso3: 'SLB', m49: '090' }
    - { iso2: 'SO', iso3: 'SOM', m49: '706' }
    - { iso2: 'ZA', iso3: 'ZAF', m49: '710' }
    - { iso2: 'GS', iso3: 'SGS', m49: '239' }
    - { iso2: 'SS', iso3: 'SSD', m49: '728' }
    - { iso2: 'ES', iso3: 'ESP', m49: '724' }
    - { iso2: 'LK', iso3: 'LKA', m49: '144' }
    - { iso2: 'SD', iso3: 'SDN', m49: '736' }
    - { iso2: 'SR', iso3: 'SUR', m49: '740' }
    - { iso2: 'SJ', iso3: 'SJM', m49: '744' }
    - { iso2: 'SZ', iso3: 'SWZ', m49: '748' }
    - { iso2: 'SE', iso3: 'SWE', m49: '752' }
    - { iso2: 'CH', iso3: 'CHE', m49: '756' }
    - { iso2: 'SY', iso3: 'SYR', m49: '760' }
    - { iso2: 'TW', iso3: 'TWN', m49: '158' }
    - { iso2: 'TJ', iso3: 'TJK', m49: '762' }
    - { iso2: 'TZ', iso3: 'TZA', m49: '834' }
    - { iso2: 'TH', iso3: 'THA', m49: '764' }
    - { iso2: 'TL', iso3: 'TLS', m49: '626' }
    - { iso2: 'TG', iso3: 'TGO', m49: '768' }
    - { iso2: 'TK', iso3: 'TKL', m49: '772' }
    - { iso2: 'TO', iso3: 'TON', m49: '776' }
    - { iso2: 'TT', iso3: 'TTO', m49: '780' }
    - { iso2: 'TN', iso3: 'TUN', m49: '788' }
    - { iso2: 'TR', iso3: 'TUR', m49: '792' }
    - { iso2: 'TM', iso3: 'TKM', m49: '795' }
    - { iso2: 'TC', iso3: 'TCA', m49: '796' }
    - { iso2: 'TV', iso3: 'TUV', m49: '798' }
    - { iso2: 'UG', iso3: 'UGA', m49: '800' }
    - { iso2: 'UA', iso3: 'UKR', m49: '804' }
    - { iso2: 'AE', iso3: 'ARE', m49: '784' }
    - { iso2: 'GB', iso3: 'GBR', m49: '826' }
    - { iso2: 'US', iso3: 'USA', m49: '840' }
    - { iso2: 'UM', iso3: 'UMI', m49: '581' }
    - { iso2: 'UY', iso3: 'URY', m49: '858' }
    - { iso2: 'UZ', iso3: 'UZB', m49: '860' }
    - { iso2: 'VU', iso3: 'VUT', m49: '548' }
    - { iso2: 'VE', iso3: 'VEN', m49: '862' }
    - { iso2: 'VN', iso3: 'VNM', m49: '704' }
    - { iso2: 'VI', iso3: 'VIR', m49: '850' }
    - { iso2: 'WF', iso3: 'WLF', m49: '876' }
    - { iso2: 'EH', iso3: 'ESH', m49: '732' }
    - { iso2: 'YE', iso3: 'YEM', m49: '887' }
    - { iso2: 'ZM', iso3: 'ZMB', m49: '894' }
    - { iso2: 'ZW', iso3: 'ZWE', m49: '716' }